### ISSUE TITLE
bold in bullet does not highlight correctly

### ISSUE THREAD

**Issue by textractor** [asciidoctor/atom-language-asciidoc#41] opened 2016-01-26 19:31 UTC
In a bullet like this:

    * Here is some text *now I want bold*.

the highlight begins at the first * and ends at the second *.  The preview, however, is correct.

The highlighter should understand that a * followed by a space at the start of a line is a bullet, unless there is exactly one other * anywhere else in the line. (Assuming no escaped or literal *).

**Comment by textractor** [comment] 2016-01-26 22:47
I've noticed another issue in this situation, where unwanted highlighting occurs. If this:

     * Something http://blah.com[link text] etc.

then the `* Something http:` is highlighted, and nothing else. The correct behavior should be no highlighting, since this is a bullet.

**Comment by nicorikken** [comment] 2016-03-08 13:40
This is a duplicate of issue #9, so it can be closed.

**Comment by ldez** [comment] 2016-04-16 01:13
The first problem is the same of #9 but the second it's not the same problem because:

In `* Something http://blah.com[link text] etc.`, the part `* Something` is parse as `markup.macro.inline.asciidoc, support.constant.asciidoc` not as `markup.bold.asciidoc`

It's the same problem as #31.

**Comment by mojavelinux** [comment] 2016-04-16 05:59
I think this is primarily what @nicorikken is working on fixing right now. He's making the matchers for constrained and unconstrained more strict so that the grammar doesn't just catch any asterisk. Having said that, we will want to make sure the case you're pointing out, @ldez, is included in the tests.

**Comment by nicorikken** [comment] 2016-05-04 06:30
This issue has been solved:
<img width="342" alt="screen shot 2016-05-04 at 08 29 31" src="https://cloud.githubusercontent.com/assets/7458098/15006556/5e74d34c-11d2-11e6-968c-9ce8551a4b95.png">
Partly because of the bullets, partly because of the URL highlighting. I therefore close this issue.

**Closed by nicorikken** 2016-05-04 06:30 UTC
Labels: duplicate, grammar
