### ISSUE TITLE
Invalid image highlight

### ISSUE THREAD

**Issue by blablatros** [asciidoctor/atom-language-asciidoc#37] opened 2015-10-22 10:51 UTC
Image highlight breaks on properly formatted urls.

* The image directive on line 19 contains only one `/` after `http:` and is correctly highlighted;
* The line 20 contains correctly formatted url, but the highlight is broken;
* On the line 21 I randomly inserted `//` in various places, however the image remained correctly highlighted.

![image](https://cloud.githubusercontent.com/assets/4815474/10663383/421117b6-78bb-11e5-9c1d-bc8cb52cfc95.png)

**Comment by nicorikken** [comment] 2016-04-22 06:33
The URL parser is known to have flaws, as is stated in the source code using comments. Maybe the URL parsing can be taken over from other Atom language packages.

**Comment by mojavelinux** [comment] 2016-04-22 06:38
Actually, the problem is that the match used for the block image macro doesn't match that in Asciidoctor core.

I think you'll find (or have already discovered) that the original grammar file was not developed by studying the Asciidoctor parser. Therefore, we should assume that all the matches we haven't yet touched need to be reviewed for accuracy.

**Comment by mojavelinux** [comment] 2016-04-22 06:38
The only rule about the target of an image in the Asciidoctor parser is that there is no whitespace after the `image::` and before the `[`.

**Comment by nicorikken** [comment] 2016-05-02 10:21
This issue is fixed in the recent commit by @ldez (as referenced), even though specific URL highlighting might be a desired feature.

**Closed by nicorikken** 2016-05-02 10:21 UTC
Labels: enhancement, grammar
