### ISSUE TITLE
Assigning source type to code block changes color properties of following text outside block

### ISSUE THREAD

**Issue by r0ckarong** [asciidoctor/atom-language-asciidoc#182] opened 2017-04-06 11:04 UTC
## Description

When you specify a code type for a code block, text that is outside of the block gets reformatted with different colors. This appears to have started in one of the recent releases. I didn't notice this with 1.7.0

## Screenshots
Set to "java"
![java](https://cloud.githubusercontent.com/assets/4920542/24751286/4261a04e-1ac9-11e7-911e-62f4461f7a9b.png)

Set to "javascript"
![javascript](https://cloud.githubusercontent.com/assets/4920542/24751284/425fc8fa-1ac9-11e7-8f3b-576dc6ae7c01.png)

No specified source type
![normal](https://cloud.githubusercontent.com/assets/4920542/24751285/4260c7f0-1ac9-11e7-8b73-d088fe33b412.png)

## Syntax example

```adoc

==== Heading Level 3

[source,java]
----
final class MonoJust<T>
extends Mono<T>
    implements Fuseable.ScalarCallable<T>, Fuseable {

  final T value;

  MonoJust(T value) {
    this.value = Objects.requireNonNull(value, "value");
  }..
----

===== Heading Level 4

TIP: This is a tip

NOTE: This is a note

IMPORTANT: This is important

WARNING: This is a warning

CAUTION: Use caution

<<<

====== Heading Level 5

Lorem ipsum dolor sit amet, consectetur adipiscing elit. _Praesent eu orci_ nec justo pulvinar aliquet et vel metus. Fusce **lacinia justo sodales ipsum** suscipit, nec link:http://www.lipsum.com/feed/html[maximus massa] aliquam. Suspendisse non porta odio. Quisque condimentum, ipsum at porta ullamcorper, ante velit fermentum lectus, at dictum turpis dui eu ante. Aenean in est eu sem pulvinar dictum. Quisque nunc velit, tincidunt ac tincidunt elementum, varius ac eros. `Aliquam egestas pulvinar massa et hendrerit`.

* Maecenas porta posuere vestibulum.
** Quisque maximus enim nec cursus mollis.
*** Ut id tortor a leo aliquet lacinia sed quis mi.

- Quisque dignissim lacus eu eros malesuada euismod.
- Sed efficitur, quam nec aliquet convallis,
- neque mi suscipit quam, ac euismod tellus tortor a nisi. Cras bibendum imperdiet tincidunt. Aliquam imperdiet, ante sed tempus ullamcorper, felis ipsum mattis ex, quis ullamcorper metus eros eget nunc. Ut ut magna lacus.
```

https://gfycat.com/EcstaticOldBluetonguelizard

**Comment by r0ckarong** [comment] 2017-04-06 11:06
Using Atom 1.15.0 on Ubuntu 16.10 LTS

**Comment by ldez** [comment] 2017-04-06 11:20
Same problem with Markdown and Java language (but not reproduce with a with JS syntax).
It's a problem with Java core package of Atom.

**Comment by ldez** [comment] 2017-04-06 11:21
Workaround: close the class with a `}`

```adoc
[source,java]
----
final class MonoJust<T> extends Mono<T> implements Fuseable.ScalarCallable<T>, Fuseable {

  final T value;

  MonoJust(T value) {
    this.value = Objects.requireNonNull(value, "value");
  }..
}
----
```

**Comment by ldez** [comment] 2017-04-06 11:26
@r0ckarong in Atom code block must be "valid" code.
If you want to use `...` comment the line: `// ...`.
If you open a structure, close it.

**Closed** 2017-04-06 11:30 UTC
Labels: Atom, grammar, support

**Comment by r0ckarong** [comment] 2017-04-06 11:45
I never knew that you have to properly close code. I just grabbed some random piece of code from the highlighter testpage to plug into my test document. 

Does that really mean I can't grab "broken" snippets of code to display in a block? I would assume the block is self contained and the contents shouldn't matter.

**Comment by ldez** [comment] 2017-04-06 11:53
The grammar parser in Atom have limit with multi-line content, if you use an element with a multi-line structure (like `{}`) you must close it.

**Comment by r0ckarong** [comment] 2017-04-06 12:15
That's good to know. Thank you.

**Comment by mojavelinux** [comment] 2017-04-06 19:11
This actually strikes me as a bit strange. We know the boundaries of the block because they are well-defined. I'm surprised that we aren't giving just the contents of the block to the syntax highlighter to highlight. In other words, the closing `----` should be a hard stop.

**Comment by mojavelinux** [comment] 2017-04-06 19:19
I guess we'd have to somehow weave into every language to abort if it sees the block delimiter. But I'm not sure if and how that can be done. Because that's how Asciidoctor works.

**Comment by ldez** [comment] 2017-04-06 19:21
It's not a surprise for me, it's the basic Atom parsing behavior with embedded language.

**Comment by ldez** [comment] 2017-04-06 19:22
`----` it's not a "hard stop", because "hard stop" doesn't exist.

**Comment by mojavelinux** [comment] 2017-04-06 19:27
I'm just saying it's surprising that Atom didn't implement a hard stop...because it exists in many lightweight markup languages.
