### ISSUE TITLE
multiple footnotes in the same paragraph don't highlight correctly

### ISSUE THREAD

**Issue by ssfrr** [asciidoctor/atom-language-asciidoc#40] opened 2015-12-15 04:05 UTC
When there are multiple footnotes in the same paragraph, the text before the first footnote gets highlighted weirdly. The change happens as soon as I type the closing bracket on the 2nd footnote.

![image](https://cloud.githubusercontent.com/assets/734386/11801754/0bbad0e6-a2b7-11e5-9c75-fce0b53e9ed6.png)

**Comment by andya9** [comment] 2016-02-10 21:19
I can confirm this

**Comment by nicorikken** [comment] 2016-04-29 06:19
This issue regarding multiple footnotes seems to be fixed in 1.0.0. I'm not sure about the highlighting itself though:
<img width="787" alt="screen shot 2016-04-29 at 08 18 30" src="https://cloud.githubusercontent.com/assets/7458098/14909388/15238348-0de3-11e6-8e23-6bffb24f593c.png">

**Comment by nicorikken** [comment] 2016-04-29 06:26
Actually @mojavelinux pointhed the issue out in issue #43 already:
> Note that the prefix `(?<=^|\\s)` doesn't apply for footnotes since a footnote can appear be directly adjacent to the text that precedes it.
So a rewrite of the inline macro is needed, or footnotes should be added separately.

**Comment by nicorikken** [comment] 2016-05-02 20:30
This issue was resolved in the current master.

**Closed by nicorikken** 2016-05-02 20:30 UTC
Labels: bug, grammar
